# based on https://github.com/pypa/cibuildwheel/blob/main/examples/github-minimal.yml
name: Build

on: [push, pull_request]

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  build_and_test:
    needs: [pre-commit]
    runs-on: ubuntu-latest
    name: Build wheel and test with pytest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12-dev"

      - name: Install build, pytest
        run: python -m pip install build pytest

      - name: Build
        run: python -m build

      - name: Build
        run: pip install dist/*.whl --force-reinstall 

      - name: pytest
        run: python -m pytest
